### PR TITLE
Added defualtYes as its always yes by default in most Distros

### PR DESCRIPTION
**Pull request by Angxddeep**

### CODE REVIEW

**Comment by devangshekhawat** [comment]
unnecessary non-significant change

**Comment by Angxddeep** [comment]
Ok, that was a bit rude, but I get it. I have used many distros in the past on every one of them while installing packages, and after it loads all the dependencies I just press enter to install and in fedora it cancels it. In every other distro it does the opposite of fedora take Arch, Debian. But ok :)

**Comment by devangshekhawat** [comment]
I apologize if it came across as rude, didnt mean it like that but the commit still seems unnecessary for me since the user just has to type in "y" to start updating 
not a significant quality of life improvement and I do believe for the average user having default yes turned off leads to better safety and makes the process of installing an update more mindful. Advanced users would not prefer that but they are advanced anyway, they know how to turn defaultyes=on

**Comment by Angxddeep** [comment]
Yeah, i actually never thought that way, maybe this the reason that the fedora team make it this way by default.

**Pull request closed without merging**
